import type { Equipment, Exercise, ExerciseType, MuscleGroup } from "./types";

export const MUSCLE_GROUPS: { id: MuscleGroup; label: string }[] = [
  { id: "abdominals", label: "Abdominals" },
  { id: "abductors", label: "Abductors" },
  { id: "adductors", label: "Adductors" },
  { id: "biceps", label: "Biceps" },
  { id: "calves", label: "Calves" },
  { id: "cardio", label: "Cardio" },
  { id: "chest", label: "Chest" },
  { id: "forearms", label: "Forearms" },
  { id: "full_body", label: "Full Body" },
  { id: "glutes", label: "Glutes" },
  { id: "hamstrings", label: "Hamstrings" },
  { id: "lats", label: "Lats" },
  { id: "lower_back", label: "Lower Back" },
  { id: "neck", label: "Neck" },
  { id: "quadriceps", label: "Quadriceps" },
  { id: "shoulders", label: "Shoulders" },
  { id: "traps", label: "Traps" },
  { id: "triceps", label: "Triceps" },
  { id: "upper_back", label: "Upper Back" },
  { id: "other", label: "Other" },
];

export const EQUIPMENT: { id: Equipment; label: string }[] = [
  { id: "none", label: "None" },
  { id: "barbell", label: "Barbell" },
  { id: "dumbbell", label: "Dumbbell" },
  { id: "kettlebell", label: "Kettlebell" },
  { id: "machine", label: "Machine" },
  { id: "cable", label: "Cable" },
  { id: "plate", label: "Plate" },
  { id: "resistance_band", label: "Resistance Band" },
  { id: "suspension", label: "Suspension Band" },
  { id: "smith_machine", label: "Smith Machine" },
  { id: "other", label: "Other" },
];

export const EXERCISE_TYPES: { id: ExerciseType; label: string; hint: string }[] = [
  { id: "weight_reps", label: "Weight & Reps", hint: "e.g. Bench Press" },
  { id: "reps_only", label: "Reps Only", hint: "e.g. Push Ups" },
  { id: "weighted_bodyweight", label: "Weighted Bodyweight", hint: "e.g. Weighted Pull Up" },
  { id: "assisted_bodyweight", label: "Assisted Bodyweight", hint: "e.g. Assisted Dip" },
  { id: "duration", label: "Duration", hint: "e.g. Plank" },
  { id: "distance_duration", label: "Distance & Duration", hint: "e.g. Running" },
  { id: "weight_distance", label: "Weight & Distance", hint: "e.g. Farmers Walk" },
];

export function muscleLabel(m: MuscleGroup): string {
  return MUSCLE_GROUPS.find((x) => x.id === m)?.label ?? m;
}
export function equipmentLabel(e: Equipment): string {
  return EQUIPMENT.find((x) => x.id === e)?.label ?? e;
}
export function exerciseTypeLabel(t: ExerciseType): string {
  return EXERCISE_TYPES.find((x) => x.id === t)?.label ?? t;
}

type Row = [string, MuscleGroup, Equipment, ExerciseType?, MuscleGroup[]?];

const W: ExerciseType = "weight_reps";

// Built-in library. Order doesn't matter; the UI sorts alphabetically.
const ROWS: Row[] = [
  // Chest
  ["Bench Press (Barbell)", "chest", "barbell", W, ["triceps", "shoulders"]],
  ["Bench Press (Dumbbell)", "chest", "dumbbell", W, ["triceps", "shoulders"]],
  ["Bench Press (Smith Machine)", "chest", "smith_machine", W, ["triceps", "shoulders"]],
  ["Incline Bench Press (Barbell)", "chest", "barbell", W, ["shoulders", "triceps"]],
  ["Incline Bench Press (Dumbbell)", "chest", "dumbbell", W, ["shoulders", "triceps"]],
  ["Incline Bench Press (Smith Machine)", "chest", "smith_machine", W, ["shoulders", "triceps"]],
  ["Decline Bench Press (Barbell)", "chest", "barbell", W, ["triceps"]],
  ["Decline Bench Press (Dumbbell)", "chest", "dumbbell", W, ["triceps"]],
  ["Chest Press (Machine)", "chest", "machine", W, ["triceps", "shoulders"]],
  ["Chest Fly (Dumbbell)", "chest", "dumbbell", W],
  ["Chest Fly (Machine)", "chest", "machine", W],
  ["Cable Fly Crossovers", "chest", "cable", W],
  ["Low Cable Fly Crossovers", "chest", "cable", W],
  ["Incline Chest Fly (Dumbbell)", "chest", "dumbbell", W],
  ["Pec Deck (Machine)", "chest", "machine", W],
  ["Push Up", "chest", "none", "reps_only", ["triceps", "shoulders"]],
  ["Push Up (Weighted)", "chest", "none", "weighted_bodyweight", ["triceps"]],
  ["Push Up - Close Grip", "chest", "none", "reps_only", ["triceps"]],
  ["Decline Push Up", "chest", "none", "reps_only", ["shoulders"]],
  ["Chest Dip", "chest", "none", "reps_only", ["triceps"]],
  ["Chest Dip (Weighted)", "chest", "none", "weighted_bodyweight", ["triceps"]],
  ["Chest Dip (Assisted)", "chest", "machine", "assisted_bodyweight", ["triceps"]],
  ["Pullover (Dumbbell)", "chest", "dumbbell", W, ["lats"]],
  ["Landmine Press", "chest", "barbell", W, ["shoulders"]],
  ["Svend Press", "chest", "plate", W],
  // Shoulders
  ["Overhead Press (Barbell)", "shoulders", "barbell", W, ["triceps"]],
  ["Overhead Press (Dumbbell)", "shoulders", "dumbbell", W, ["triceps"]],
  ["Shoulder Press (Machine)", "shoulders", "machine", W, ["triceps"]],
  ["Seated Overhead Press (Barbell)", "shoulders", "barbell", W, ["triceps"]],
  ["Seated Shoulder Press (Dumbbell)", "shoulders", "dumbbell", W, ["triceps"]],
  ["Arnold Press (Dumbbell)", "shoulders", "dumbbell", W, ["triceps"]],
  ["Push Press", "shoulders", "barbell", W, ["triceps", "quadriceps"]],
  ["Lateral Raise (Dumbbell)", "shoulders", "dumbbell", W],
  ["Lateral Raise (Cable)", "shoulders", "cable", W],
  ["Lateral Raise (Machine)", "shoulders", "machine", W],
  ["Front Raise (Dumbbell)", "shoulders", "dumbbell", W],
  ["Front Raise (Barbell)", "shoulders", "barbell", W],
  ["Front Raise (Cable)", "shoulders", "cable", W],
  ["Front Raise (Plate)", "shoulders", "plate", W],
  ["Rear Delt Reverse Fly (Dumbbell)", "shoulders", "dumbbell", W, ["upper_back"]],
  ["Rear Delt Reverse Fly (Machine)", "shoulders", "machine", W, ["upper_back"]],
  ["Rear Delt Reverse Fly (Cable)", "shoulders", "cable", W, ["upper_back"]],
  ["Face Pull", "shoulders", "cable", W, ["upper_back", "traps"]],
  ["Upright Row (Barbell)", "shoulders", "barbell", W, ["traps"]],
  ["Upright Row (Dumbbell)", "shoulders", "dumbbell", W, ["traps"]],
  ["Upright Row (Cable)", "shoulders", "cable", W, ["traps"]],
  ["Handstand Push Up", "shoulders", "none", "reps_only", ["triceps"]],
  ["Pike Push Up", "shoulders", "none", "reps_only", ["triceps"]],
  ["Shrug (Barbell)", "traps", "barbell", W],
  ["Shrug (Dumbbell)", "traps", "dumbbell", W],
  ["Shrug (Machine)", "traps", "machine", W],
  ["Shrug (Smith Machine)", "traps", "smith_machine", W],
  // Back
  ["Deadlift (Barbell)", "lower_back", "barbell", W, ["glutes", "hamstrings", "upper_back"]],
  ["Deadlift (Trap Bar)", "lower_back", "barbell", W, ["glutes", "quadriceps"]],
  ["Deadlift (Dumbbell)", "lower_back", "dumbbell", W, ["glutes", "hamstrings"]],
  ["Sumo Deadlift", "glutes", "barbell", W, ["hamstrings", "quadriceps", "lower_back"]],
  ["Romanian Deadlift (Barbell)", "hamstrings", "barbell", W, ["glutes", "lower_back"]],
  ["Romanian Deadlift (Dumbbell)", "hamstrings", "dumbbell", W, ["glutes", "lower_back"]],
  ["Stiff Leg Deadlift (Barbell)", "hamstrings", "barbell", W, ["glutes", "lower_back"]],
  ["Rack Pull", "lower_back", "barbell", W, ["traps", "glutes"]],
  ["Good Morning (Barbell)", "hamstrings", "barbell", W, ["lower_back", "glutes"]],
  ["Back Extension (Hyperextension)", "lower_back", "none", "reps_only", ["glutes", "hamstrings"]],
  ["Back Extension (Weighted Hyperextension)", "lower_back", "plate", "weighted_bodyweight", ["glutes"]],
  ["Back Extension (Machine)", "lower_back", "machine", W],
  ["Superman", "lower_back", "none", "reps_only"],
  ["Pull Up", "lats", "none", "reps_only", ["biceps", "upper_back"]],
  ["Pull Up (Weighted)", "lats", "none", "weighted_bodyweight", ["biceps"]],
  ["Pull Up (Assisted)", "lats", "machine", "assisted_bodyweight", ["biceps"]],
  ["Pull Up (Band)", "lats", "resistance_band", "reps_only", ["biceps"]],
  ["Chin Up", "lats", "none", "reps_only", ["biceps"]],
  ["Chin Up (Weighted)", "lats", "none", "weighted_bodyweight", ["biceps"]],
  ["Chin Up (Assisted)", "lats", "machine", "assisted_bodyweight", ["biceps"]],
  ["Neutral Grip Pull Up", "lats", "none", "reps_only", ["biceps"]],
  ["Muscle Up", "lats", "none", "reps_only", ["chest", "triceps"]],
  ["Lat Pulldown (Cable)", "lats", "cable", W, ["biceps", "upper_back"]],
  ["Lat Pulldown (Machine)", "lats", "machine", W, ["biceps"]],
  ["Lat Pulldown - Close Grip (Cable)", "lats", "cable", W, ["biceps"]],
  ["Lat Pulldown - Underhand (Cable)", "lats", "cable", W, ["biceps"]],
  ["Lat Pulldown - Wide Grip (Cable)", "lats", "cable", W, ["upper_back"]],
  ["Lat Pulldown - Single Arm (Cable)", "lats", "cable", W, ["biceps"]],
  ["Straight Arm Lat Pulldown (Cable)", "lats", "cable", W],
  ["Bent Over Row (Barbell)", "upper_back", "barbell", W, ["lats", "biceps"]],
  ["Bent Over Row - Underhand (Barbell)", "upper_back", "barbell", W, ["lats", "biceps"]],
  ["Bent Over Row (Dumbbell)", "upper_back", "dumbbell", W, ["lats", "biceps"]],
  ["Dumbbell Row", "upper_back", "dumbbell", W, ["lats", "biceps"]],
  ["Pendlay Row (Barbell)", "upper_back", "barbell", W, ["lats"]],
  ["T Bar Row", "upper_back", "barbell", W, ["lats", "biceps"]],
  ["Seated Cable Row - V Grip (Cable)", "upper_back", "cable", W, ["lats", "biceps"]],
  ["Seated Cable Row - Bar Grip (Cable)", "upper_back", "cable", W, ["lats", "biceps"]],
  ["Seated Row (Machine)", "upper_back", "machine", W, ["lats", "biceps"]],
  ["Iso-Lateral Row (Machine)", "upper_back", "machine", W, ["lats", "biceps"]],
  ["Chest Supported Incline Row (Dumbbell)", "upper_back", "dumbbell", W, ["lats"]],
  ["Meadows Row", "upper_back", "barbell", W, ["lats"]],
  ["Inverted Row", "upper_back", "none", "reps_only", ["biceps"]],
  ["Inverted Row (Suspension)", "upper_back", "suspension", "reps_only", ["biceps"]],
  ["Kroc Row", "upper_back", "dumbbell", W, ["lats"]],
  ["Single Arm Cable Row", "upper_back", "cable", W, ["lats"]],
  ["Reverse Grip Lat Pulldown (Machine)", "lats", "machine", W, ["biceps"]],
  // Biceps
  ["Bicep Curl (Barbell)", "biceps", "barbell", W, ["forearms"]],
  ["Bicep Curl (Dumbbell)", "biceps", "dumbbell", W, ["forearms"]],
  ["Bicep Curl (Cable)", "biceps", "cable", W],
  ["Bicep Curl (Machine)", "biceps", "machine", W],
  ["EZ Bar Curl", "biceps", "barbell", W, ["forearms"]],
  ["Hammer Curl (Dumbbell)", "biceps", "dumbbell", W, ["forearms"]],
  ["Hammer Curl (Cable)", "biceps", "cable", W, ["forearms"]],
  ["Preacher Curl (Barbell)", "biceps", "barbell", W],
  ["Preacher Curl (Dumbbell)", "biceps", "dumbbell", W],
  ["Preacher Curl (Machine)", "biceps", "machine", W],
  ["Incline Curl (Dumbbell)", "biceps", "dumbbell", W],
  ["Concentration Curl", "biceps", "dumbbell", W],
  ["Spider Curl (Dumbbell)", "biceps", "dumbbell", W],
  ["Spider Curl (Barbell)", "biceps", "barbell", W],
  ["Drag Curl", "biceps", "barbell", W],
  ["Zottman Curl", "biceps", "dumbbell", W, ["forearms"]],
  ["Bayesian Curl (Cable)", "biceps", "cable", W],
  ["Reverse Curl (Barbell)", "forearms", "barbell", W, ["biceps"]],
  ["Reverse Curl (Dumbbell)", "forearms", "dumbbell", W, ["biceps"]],
  ["Wrist Curl (Barbell)", "forearms", "barbell", W],
  ["Wrist Curl (Dumbbell)", "forearms", "dumbbell", W],
  ["Reverse Wrist Curl (Barbell)", "forearms", "barbell", W],
  ["Farmers Walk", "forearms", "dumbbell", "weight_distance", ["traps", "full_body"]],
  ["Dead Hang", "forearms", "none", "duration", ["lats"]],
  ["Plate Pinch", "forearms", "plate", "duration"],
  // Triceps
  ["Triceps Pushdown (Cable)", "triceps", "cable", W],
  ["Triceps Rope Pushdown", "triceps", "cable", W],
  ["Triceps Pushdown - Straight Bar", "triceps", "cable", W],
  ["Triceps Extension (Cable)", "triceps", "cable", W],
  ["Triceps Extension (Dumbbell)", "triceps", "dumbbell", W],
  ["Triceps Extension (Barbell)", "triceps", "barbell", W],
  ["Triceps Extension (Machine)", "triceps", "machine", W],
  ["Overhead Triceps Extension (Cable)", "triceps", "cable", W],
  ["Overhead Triceps Extension (Dumbbell)", "triceps", "dumbbell", W],
  ["Skullcrusher (Barbell)", "triceps", "barbell", W],
  ["Skullcrusher (Dumbbell)", "triceps", "dumbbell", W],
  ["Triceps Kickback (Dumbbell)", "triceps", "dumbbell", W],
  ["Triceps Kickback (Cable)", "triceps", "cable", W],
  ["Close Grip Bench Press (Barbell)", "triceps", "barbell", W, ["chest", "shoulders"]],
  ["JM Press", "triceps", "barbell", W, ["chest"]],
  ["Triceps Dip", "triceps", "none", "reps_only", ["chest"]],
  ["Triceps Dip (Weighted)", "triceps", "none", "weighted_bodyweight", ["chest"]],
  ["Triceps Dip (Assisted)", "triceps", "machine", "assisted_bodyweight", ["chest"]],
  ["Bench Dip", "triceps", "none", "reps_only"],
  ["Diamond Push Up", "triceps", "none", "reps_only", ["chest"]],
  ["Tate Press", "triceps", "dumbbell", W],
  // Legs
  ["Squat (Barbell)", "quadriceps", "barbell", W, ["glutes", "hamstrings", "lower_back"]],
  ["Squat (Dumbbell)", "quadriceps", "dumbbell", W, ["glutes"]],
  ["Squat (Smith Machine)", "quadriceps", "smith_machine", W, ["glutes"]],
  ["Squat (Bodyweight)", "quadriceps", "none", "reps_only", ["glutes"]],
  ["Front Squat", "quadriceps", "barbell", W, ["glutes", "abdominals"]],
  ["Goblet Squat", "quadriceps", "dumbbell", W, ["glutes"]],
  ["Goblet Squat (Kettlebell)", "quadriceps", "kettlebell", W, ["glutes"]],
  ["Box Squat (Barbell)", "quadriceps", "barbell", W, ["glutes"]],
  ["Pause Squat (Barbell)", "quadriceps", "barbell", W, ["glutes"]],
  ["Zercher Squat", "quadriceps", "barbell", W, ["glutes", "abdominals"]],
  ["Hack Squat (Machine)", "quadriceps", "machine", W, ["glutes"]],
  ["Hack Squat (Barbell)", "quadriceps", "barbell", W, ["glutes"]],
  ["Pendulum Squat (Machine)", "quadriceps", "machine", W, ["glutes"]],
  ["Belt Squat", "quadriceps", "machine", W, ["glutes"]],
  ["Leg Press (Machine)", "quadriceps", "machine", W, ["glutes", "hamstrings"]],
  ["Leg Press Horizontal (Machine)", "quadriceps", "machine", W, ["glutes"]],
  ["Single Leg Press (Machine)", "quadriceps", "machine", W, ["glutes"]],
  ["Leg Extension (Machine)", "quadriceps", "machine", W],
  ["Sissy Squat", "quadriceps", "none", "reps_only"],
  ["Lunge (Barbell)", "quadriceps", "barbell", W, ["glutes", "hamstrings"]],
  ["Lunge (Dumbbell)", "quadriceps", "dumbbell", W, ["glutes", "hamstrings"]],
  ["Lunge (Bodyweight)", "quadriceps", "none", "reps_only", ["glutes"]],
  ["Walking Lunge (Dumbbell)", "quadriceps", "dumbbell", W, ["glutes"]],
  ["Reverse Lunge (Dumbbell)", "quadriceps", "dumbbell", W, ["glutes"]],
  ["Reverse Lunge (Barbell)", "quadriceps", "barbell", W, ["glutes"]],
  ["Bulgarian Split Squat", "quadriceps", "dumbbell", W, ["glutes", "hamstrings"]],
  ["Bulgarian Split Squat (Barbell)", "quadriceps", "barbell", W, ["glutes"]],
  ["Split Squat (Bodyweight)", "quadriceps", "none", "reps_only", ["glutes"]],
  ["Step Up", "quadriceps", "dumbbell", W, ["glutes"]],
  ["Pistol Squat", "quadriceps", "none", "reps_only", ["glutes"]],
  ["Wall Sit", "quadriceps", "none", "duration"],
  ["Leg Curl (Lying, Machine)", "hamstrings", "machine", W],
  ["Leg Curl (Seated, Machine)", "hamstrings", "machine", W],
  ["Leg Curl (Standing, Machine)", "hamstrings", "machine", W],
  ["Nordic Hamstring Curl", "hamstrings", "none", "reps_only", ["glutes"]],
  ["Glute Ham Raise", "hamstrings", "none", "reps_only", ["glutes"]],
  ["Single Leg Romanian Deadlift (Dumbbell)", "hamstrings", "dumbbell", W, ["glutes"]],
  ["Kettlebell Swing", "hamstrings", "kettlebell", W, ["glutes", "lower_back"]],
  ["Hip Thrust (Barbell)", "glutes", "barbell", W, ["hamstrings"]],
  ["Hip Thrust (Machine)", "glutes", "machine", W, ["hamstrings"]],
  ["Hip Thrust (Bodyweight)", "glutes", "none", "reps_only", ["hamstrings"]],
  ["Glute Bridge", "glutes", "none", "reps_only", ["hamstrings"]],
  ["Single Leg Glute Bridge", "glutes", "none", "reps_only"],
  ["Glute Kickback (Cable)", "glutes", "cable", W],
  ["Glute Kickback (Machine)", "glutes", "machine", W],
  ["Cable Pull Through", "glutes", "cable", W, ["hamstrings"]],
  ["Hip Abduction (Machine)", "abductors", "machine", W, ["glutes"]],
  ["Hip Adduction (Machine)", "adductors", "machine", W],
  ["Hip Abduction (Cable)", "abductors", "cable", W],
  ["Hip Adduction (Cable)", "adductors", "cable", W],
  ["Clamshell", "abductors", "resistance_band", "reps_only", ["glutes"]],
  ["Lateral Band Walk", "abductors", "resistance_band", "reps_only", ["glutes"]],
  ["Standing Calf Raise (Machine)", "calves", "machine", W],
  ["Standing Calf Raise (Dumbbell)", "calves", "dumbbell", W],
  ["Standing Calf Raise (Barbell)", "calves", "barbell", W],
  ["Standing Calf Raise (Smith Machine)", "calves", "smith_machine", W],
  ["Standing Calf Raise (Bodyweight)", "calves", "none", "reps_only"],
  ["Seated Calf Raise (Machine)", "calves", "machine", W],
  ["Calf Press (Leg Press Machine)", "calves", "machine", W],
  ["Donkey Calf Raise", "calves", "machine", W],
  ["Single Leg Calf Raise", "calves", "none", "reps_only"],
  ["Tibialis Raise", "calves", "none", "reps_only"],
  // Core
  ["Crunch", "abdominals", "none", "reps_only"],
  ["Crunch (Machine)", "abdominals", "machine", W],
  ["Cable Crunch", "abdominals", "cable", W],
  ["Decline Crunch", "abdominals", "none", "reps_only"],
  ["Bicycle Crunch", "abdominals", "none", "reps_only"],
  ["Reverse Crunch", "abdominals", "none", "reps_only"],
  ["Sit Up", "abdominals", "none", "reps_only"],
  ["Sit Up (Weighted)", "abdominals", "plate", "weighted_bodyweight"],
  ["Plank", "abdominals", "none", "duration"],
  ["Side Plank", "abdominals", "none", "duration"],
  ["Hanging Leg Raise", "abdominals", "none", "reps_only"],
  ["Hanging Knee Raise", "abdominals", "none", "reps_only"],
  ["Lying Leg Raise", "abdominals", "none", "reps_only"],
  ["Captain's Chair Leg Raise", "abdominals", "machine", "reps_only"],
  ["Toes To Bar", "abdominals", "none", "reps_only"],
  ["Ab Wheel Rollout", "abdominals", "other", "reps_only"],
  ["Russian Twist", "abdominals", "plate", W],
  ["Russian Twist (Bodyweight)", "abdominals", "none", "reps_only"],
  ["Mountain Climber", "abdominals", "none", "reps_only"],
  ["Dead Bug", "abdominals", "none", "reps_only"],
  ["Hollow Hold", "abdominals", "none", "duration"],
  ["V Up", "abdominals", "none", "reps_only"],
  ["Flutter Kicks", "abdominals", "none", "reps_only"],
  ["Cable Woodchopper", "abdominals", "cable", W],
  ["Pallof Press", "abdominals", "cable", W],
  ["Dragon Flag", "abdominals", "none", "reps_only"],
  ["L-Sit Hold", "abdominals", "none", "duration"],
  ["Side Bend (Dumbbell)", "abdominals", "dumbbell", W],
  ["Neck Curl", "neck", "plate", W],
  ["Neck Extension", "neck", "plate", W],
  // Full body / olympic
  ["Clean", "full_body", "barbell", W, ["quadriceps", "glutes", "traps"]],
  ["Power Clean", "full_body", "barbell", W, ["quadriceps", "glutes", "traps"]],
  ["Hang Clean", "full_body", "barbell", W, ["quadriceps", "traps"]],
  ["Clean and Jerk", "full_body", "barbell", W, ["shoulders", "quadriceps"]],
  ["Clean and Press", "full_body", "barbell", W, ["shoulders"]],
  ["Snatch", "full_body", "barbell", W, ["shoulders", "quadriceps"]],
  ["Power Snatch", "full_body", "barbell", W, ["shoulders", "quadriceps"]],
  ["Thruster (Barbell)", "full_body", "barbell", W, ["quadriceps", "shoulders"]],
  ["Thruster (Dumbbell)", "full_body", "dumbbell", W, ["quadriceps", "shoulders"]],
  ["Kettlebell Clean", "full_body", "kettlebell", W],
  ["Kettlebell Snatch", "full_body", "kettlebell", W, ["shoulders"]],
  ["Turkish Get Up", "full_body", "kettlebell", W, ["shoulders", "abdominals"]],
  ["Burpee", "full_body", "none", "reps_only", ["cardio"]],
  ["Man Maker", "full_body", "dumbbell", W],
  ["Sled Push", "full_body", "other", "weight_distance", ["quadriceps", "glutes"]],
  ["Sled Pull", "full_body", "other", "weight_distance", ["hamstrings", "upper_back"]],
  ["Battle Ropes", "full_body", "other", "duration", ["shoulders", "cardio"]],
  ["Wall Ball", "full_body", "other", W, ["quadriceps", "shoulders"]],
  ["Box Jump", "quadriceps", "other", "reps_only", ["glutes", "calves"]],
  ["Medicine Ball Slam", "full_body", "other", W, ["abdominals"]],
  ["Suitcase Carry", "abdominals", "dumbbell", "weight_distance", ["forearms"]],
  // Cardio
  ["Running", "cardio", "none", "distance_duration"],
  ["Treadmill", "cardio", "machine", "distance_duration"],
  ["Walking", "cardio", "none", "distance_duration"],
  ["Cycling", "cardio", "machine", "distance_duration"],
  ["Stationary Bike", "cardio", "machine", "distance_duration"],
  ["Rowing Machine", "cardio", "machine", "distance_duration", ["upper_back"]],
  ["Elliptical Trainer", "cardio", "machine", "distance_duration"],
  ["Stair Climber", "cardio", "machine", "duration", ["quadriceps", "glutes"]],
  ["Assault Bike", "cardio", "machine", "duration"],
  ["Ski Erg", "cardio", "machine", "distance_duration", ["lats"]],
  ["Jump Rope", "cardio", "other", "duration", ["calves"]],
  ["Swimming", "cardio", "none", "distance_duration"],
  ["Hiking", "cardio", "none", "distance_duration"],
  ["Jumping Jack", "cardio", "none", "reps_only"],
  ["High Knees", "cardio", "none", "duration"],
  ["Sprint", "cardio", "none", "distance_duration"],
  // Stretching / mobility
  ["Stretching", "other", "none", "duration"],
  ["Foam Rolling", "other", "other", "duration"],
  ["Yoga", "other", "none", "duration"],
  ["Cat Cow", "other", "none", "reps_only"],
  ["World's Greatest Stretch", "other", "none", "reps_only"],
  ["Hip Flexor Stretch", "other", "none", "duration"],
  ["Pigeon Pose", "other", "none", "duration"],
  ["Hamstring Stretch", "hamstrings", "none", "duration"],
  ["Chest Stretch", "chest", "none", "duration"],
  ["Shoulder Dislocates", "shoulders", "other", "reps_only"],
  ["Band Pull Apart", "upper_back", "resistance_band", "reps_only", ["shoulders"]],
];

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export const BUILTIN_EXERCISES: Exercise[] = ROWS.map(([name, muscleGroup, equipment, type, secondary]) => ({
  id: "ex_" + slug(name),
  name,
  muscleGroup,
  equipment,
  type: type ?? W,
  secondaryMuscles: secondary ?? [],
}));

export const BUILTIN_BY_ID: Record<string, Exercise> = Object.fromEntries(
  BUILTIN_EXERCISES.map((e) => [e.id, e])
);

export function exerciseIdFor(name: string): string {
  return "ex_" + slug(name);
}
